name: Scrape Eliteprospects for team rosters
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
jobs:
  Scrape-Eliteprospects:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy
    - name: Scrape Eliteprospects
      run: |
        scrapy runspider elitescrape/elitescrape/spiders/elite_spider.py
        scrapy runspider elitescrape/elitescrape/spiders/team_stripes.py
        git config --global user.name 'Bot'
        git config --global user.email 'bot@katzefudder.de'
        touch del2.txt
        touch team_stripes.txt
        git add del2.txt
        git add team_stripes.txt
        git commit -m "automated scraping of DEL2 rosters"
        git push
